name: Platform independent compilation

on:
  push:
    branches:
      - feature/freertos

jobs:

  compile-tests:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: get gcc compiler
      run: |
        sudo apt update
        sudo apt install build-essential
    - name: Get ArduinoJson
      run: wget -Uri https://github.com/bblanchon/ArduinoJson/releases/download/v6.19.4/ArduinoJson-v6.19.4.h -O ./src/ArduinoJson.h
    - name: Compile
      run: g++ -std=c++14 -I ./src -g $(find ./src -type f -iregex ".*\.cpp") -DAO_CUSTOM_WS -DAO_CUSTOM_CONSOLE -DAO_CUSTOM_UPDATER -DAO_CUSTOM_RESET -DAO_DEACTIVATE_FLASH -DAO_USE_FILEAPI=ESPIDF_SPIFFS -DAO_DBG_LEVEL=AO_DL_DEBUG -DAO_TRAFFIC_OUT -DAO_FILENAME_PREFIX='"/ao_store"' -o ./output -Wall
