name: Test Runner

on:
  push:
    branches:
      - develop

jobs:

  compile-and-run:
    name: Automated Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Get gcc compiler
      run: |
        sudo apt update
        sudo apt install build-essential
        sudo apt -y install gcc-9 g++-9
        g++ --version
        echo "g++ version must be 9.4.0"
    - name: Get ArduinoJson
      run: wget -Uri https://github.com/bblanchon/ArduinoJson/releases/download/v6.19.4/ArduinoJson-v6.19.4.h -O ./src/ArduinoJson.h
    - name: Compile
      run: g++ -std=c++14 -I ./src $(find ./src ./tests -type f -iregex ".*\.cpp") -DAO_CUSTOM_WS -DAO_CUSTOM_UPDATER -DAO_CUSTOM_RESET -DAO_USE_FILEAPI=POSIX_FILEAPI -DAO_DBG_LEVEL=AO_DL_DEBUG -DAO_TRAFFIC_OUT -DAO_FILENAME_PREFIX='"./ao_store"' -DAO_PLATFORM=AO_PLATFORM_UNIX -DAO_CUSTOM_TIMER -DAO_DEACTIVATE_FLASH_SMARTCHARGING -o ./output -Wall
    - name: Run tests
      run: ./output
